import{NextResponse}from"next/server";import{getChatGPTUser}from"../../chatgpt-auth";
const sql=`CREATE TABLE IF NOT EXISTS course_progress (user_email TEXT NOT NULL,course_id TEXT NOT NULL,completed_units INTEGER NOT NULL DEFAULT 0,passed INTEGER NOT NULL DEFAULT 0,best_score INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(user_email,course_id))`;
const config={"claude-01":{units:6,prerequisite:null},"claude-code":{units:7,prerequisite:"claude-01"}}as const;
type CourseId=keyof typeof config;
async function db(){const{env}=await import("cloudflare:workers");await env.DB.prepare(sql).run();return env.DB}
function courseId(value:string|null):CourseId{return value&&value in config?value as CourseId:"claude-01"}
async function isUnlocked(d:Awaited<ReturnType<typeof db>>,email:string,id:CourseId){const pre=config[id].prerequisite;if(!pre)return true;const row=await d.prepare("SELECT passed FROM course_progress WHERE user_email=? AND course_id=?").bind(email,pre).first<{passed:number}>();return!!row?.passed}
export async function GET(req:Request){const u=await getChatGPTUser();if(!u)return NextResponse.json({error:"Unauthorized"},{status:401});const id=courseId(new URL(req.url).searchParams.get("courseId")),d=await db();if(!await isUnlocked(d,u.email,id))return NextResponse.json({error:"Complete the prerequisite course first"},{status:403});const r=await d.prepare("SELECT completed_units,passed,best_score FROM course_progress WHERE user_email=? AND course_id=?").bind(u.email,id).first<{completed_units:number;passed:number;best_score:number}>();return NextResponse.json({completedUnits:r?.completed_units??0,passed:!!r?.passed,bestScore:r?.best_score??0})}
export async function POST(req:Request){const u=await getChatGPTUser();if(!u)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json()as{courseId?:string;completedUnits?:number;passed?:boolean;bestScore?:number},id=courseId(b.courseId??null),d=await db();if(!await isUnlocked(d,u.email,id))return NextResponse.json({error:"Complete the prerequisite course first"},{status:403});const r=await d.prepare("SELECT completed_units,passed,best_score FROM course_progress WHERE user_email=? AND course_id=?").bind(u.email,id).first<{completed_units:number;passed:number;best_score:number}>(),old=r?.completed_units??0,total=config[id].units,c=Math.min(Math.max(old,Math.min(total,+b.completedUnits!||old)),old+1),score=Math.max(r?.best_score??0,Math.min(8,+b.bestScore!||0)),passed=!!r?.passed||(c===total&&!!b.passed&&score>=6);await d.prepare("INSERT INTO course_progress VALUES(?,?,?,?,?,?) ON CONFLICT(user_email,course_id) DO UPDATE SET completed_units=excluded.completed_units,passed=excluded.passed,best_score=excluded.best_score,updated_at=excluded.updated_at").bind(u.email,id,c,passed?1:0,score,new Date().toISOString()).run();return NextResponse.json({completedUnits:c,passed,bestScore:score})}
